<a href="https://colab.research.google.com/github/nainarbala/numpy_and_pandas/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [11]:
a1 = np.array([1,2,3,5])
print(a1)

a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

a3 = np.array([[[1,1,1],[2,2,2],[3,3,3]]])
print(a3)

zeros = np.zeros((5,10))
print(zeros)

print(np.ones((2,3)))

print(np.arange(0, 10, 2))

[1 2 3 5]
[[1 2 3]
 [4 5 6]]
[[[1 1 1]
  [2 2 2]
  [3 3 3]]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]


In [12]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
#elements from index 1 to 3
print("Range of Elements:",arr[1:4])

#all rows, second column
print("Multidimensional Slicing:", arr[:, 1])

[[1 2 3]
 [4 5 6]]
Range of Elements: [[4 5 6]]
Multidimensional Slicing: [2 5]


In [15]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Integer array indexing
indices = np.array([1, 3, 5])
print ("Integer array indexing:", arr[indices])

# boolean array indexing
cond = arr > 0
print("cond", cond, type(cond))
print ("\nElements greater than 0:\n", arr[cond])

Integer array indexing: [20 40 60]
cond [ True  True  True  True  True  True  True  True  True  True] <class 'numpy.ndarray'>

Elements greater than 0:
 [ 10  20  30  40  50  60  70  80  90 100]


In [16]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Addition
add = x + y
print("Addition:",add)

# Subtraction
subtract = x - y
print("substration:",subtract)

# Multiplication
multiply = x * y
print("multiplication:",multiply)

# Division
divide = x / y
print("division:", divide)

Addition: [5 7 9]
substration: [-3 -3 -3]
multiplication: [ 4 10 18]
division: [0.25 0.4  0.5 ]


NumPy Sorting Arrays
We can use a simple np.sort() method for sorting Python NumPy arrays.

In [19]:
import numpy as np

# set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

# Values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

# Creating array
arr = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n",
            np.sort(arr, order = 'name'))

print ("Array sorted by graduation year and then cgpa:\n",
                np.sort(arr, order = ['grad_year', 'cgpa']))


Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


In [21]:
# Python program to demonstrate
# basic array characteristics
import numpy as np

# Creating array object
arr = np.array( [[ 1, 2, 3],
                [ 4, 2, 5]] )

print(type(arr))
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

<class 'numpy.ndarray'>
(2, 3)
2
6
int64


### Ways to Create Numpy Arrays


In [22]:
import numpy as np

zeros_array = np.zeros((2, 3))
ones_array = np.ones((3, 3))
constant_array = np.full((2, 2), 7)
range_array = np.arange(0, 10, 2)  # start, stop, step
linspace_array = np.linspace(0, 1, 5)  # start, stop, num

print("Zero Array:","\n",zeros_array)
print("Ones Array:","\n",ones_array)
print("Constant Array:","\n",constant_array)
print("Range Array:","\n",range_array)
print("Linspace Array:","\n",linspace_array)


Zero Array: 
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Constant Array: 
 [[7 7]
 [7 7]]
Range Array: 
 [0 2 4 6 8]
Linspace Array: 
 [0.   0.25 0.5  0.75 1.  ]


### Accessing Elements in Multidimensional Arrays

In [24]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix[1, 2])


import numpy as np

cube = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],

                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]])

print(cube[1, 2, 0])

6
16


### Slicing Arrays

In [25]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5])

print(arr[1:4])

[1 2 3]


### Reshape NumPy Array

In [26]:
# importing numpy
import numpy as np

# creating a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

# printing array
print("Array : " + str(array))

# length of array
n = array.size

# N-D array N dimension
N = 4

# calculating M
M = n//N

# reshaping numpy array
# converting it to 2-D from 1-D array
reshaped1 = array.reshape((N, M))

# printing reshaped array
print("First Reshaped Array : ")
print(reshaped1)

# creating another reshaped array
reshaped2 = np.reshape(array, (2, 8))

# printing reshaped array
print("Second Reshaped Array : ")
print(reshaped2)

Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
First Reshaped Array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Second Reshaped Array : 
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


### Python | Numpy numpy.resize()


# importing the python module numpy
import numpy as np

# Making a random array
gfg = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array permanently
gfg.resize(2, 3)

print(gfg)

### numpy.stack() in Python

In [27]:
import numpy as np

# input array
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stacking 2 1-d arrays
c = np.stack((a, b),axis=0)
print(c)

[[1 2 3]
 [4 5 6]]


### Broadcasting in Conditional Operations


In [28]:
import numpy as np

ages = np.array([12, 24, 35, 45, 60, 72])

age_group = np.array(["Adult", "Minor"])

result = np.where(ages > 18, age_group[0], age_group[1])

print(result)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


### Consider a real-world scenario where we need to calculate the total calories in foods based on the amount of fats, proteins and carbohydrates. Each nutrient has a specific caloric value per gram. \

Fats: 9 calories per gram (CPG)
Proteins: 4 CPG
Carbohydrates: 4 CPG


Left table shows the original data with food items and their respective grams of fats, proteins and carbs. The array [3, 3, 8] represents the caloric values per gram for fats, proteins and carbs respectively. This array is being broadcast to match the dimensions of the original data and arrow indicates the broadcasting operation.

Broadcasting array is multiplied element-wise with each row of the original data.
As a result right table shows the result of the multiplication where each cell represents the caloric contribution of that specific nutrient in the food item.

https://media.geeksforgeeks.org/wp-content/uploads/20250512173302159001/broad1.webp

In [29]:
import numpy as np
food_data = np.array([[0.8, 2.9, 3.9],
                      [52.4, 23.6, 36.5],
                      [55.2, 31.7, 23.9],
                      [14.4, 11, 4.9]])

caloric_values = np.array([3, 3, 8])

caloric_matrix = caloric_values

calorie_breakdown = food_data * caloric_matrix
print(calorie_breakdown)

[[  2.4   8.7  31.2]
 [157.2  70.8 292. ]
 [165.6  95.1 191.2]
 [ 43.2  33.   39.2]]


In [37]:
import numpy as np

temperatures = np.array([
    [30, 32, 34, 33, 31],
    [25, 27, 29, 28, 26],
    [20, 22, 24, 23, 21]
])

corrections = np.array([1.5, -0.5, 2.0])

adjusted_temperatures = temperatures + corrections[:, np.newaxis]
print(adjusted_temperatures)



[[31.5 33.5 35.5 34.5 32.5]
 [24.5 26.5 28.5 27.5 25.5]
 [22.  24.  26.  25.  23. ]]
