<a href="https://colab.research.google.com/github/nainarbala/numpy_and_pandas/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [11]:
a1 = np.array([1,2,3,5])
print(a1)

a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

a3 = np.array([[[1,1,1],[2,2,2],[3,3,3]]])
print(a3)

zeros = np.zeros((5,10))
print(zeros)

print(np.ones((2,3)))

print(np.arange(0, 10, 2))

[1 2 3 5]
[[1 2 3]
 [4 5 6]]
[[[1 1 1]
  [2 2 2]
  [3 3 3]]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]


In [12]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
#elements from index 1 to 3
print("Range of Elements:",arr[1:4])

#all rows, second column
print("Multidimensional Slicing:", arr[:, 1])

[[1 2 3]
 [4 5 6]]
Range of Elements: [[4 5 6]]
Multidimensional Slicing: [2 5]


In [15]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Integer array indexing
indices = np.array([1, 3, 5])
print ("Integer array indexing:", arr[indices])

# boolean array indexing
cond = arr > 0
print("cond", cond, type(cond))
print ("\nElements greater than 0:\n", arr[cond])

Integer array indexing: [20 40 60]
cond [ True  True  True  True  True  True  True  True  True  True] <class 'numpy.ndarray'>

Elements greater than 0:
 [ 10  20  30  40  50  60  70  80  90 100]
